// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: follow.proto

package followclient

import (
	"context"

	"xls/app/follow/rpc/follow"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Error            = follow.Error
	FollowRequest    = follow.FollowRequest
	FollowResponse   = follow.FollowResponse
	UnFollowRequest  = follow.UnFollowRequest
	UnFollowResponse = follow.UnFollowResponse

	Follow interface {
		Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
		UnFollow(ctx context.Context, in *UnFollowRequest, opts ...grpc.CallOption) (*UnFollowResponse, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

func (m *defaultFollow) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	client := follow.NewFollowClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultFollow) UnFollow(ctx context.Context, in *UnFollowRequest, opts ...grpc.CallOption) (*UnFollowResponse, error) {
	client := follow.NewFollowClient(m.cli.Conn())
	return client.UnFollow(ctx, in, opts...)
}
