// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: follow.proto

package server

import (
	"context"

	"xls/app/follow/rpc/follow"
	"xls/app/follow/rpc/internal/logic"
	"xls/app/follow/rpc/internal/svc"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	follow.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) Follow(ctx context.Context, in *follow.FollowRequest) (*follow.FollowResponse, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}
