// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: agent.proto

package server

import (
	"context"

	"xls/app/agent/rpc/agent"
	"xls/app/agent/rpc/internal/logic"
	"xls/app/agent/rpc/internal/svc"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

// 健康检查
func (s *AgentServer) HealthCheck(ctx context.Context, in *agent.HealthCheckRequest) (*agent.HealthCheckResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}

// 对话
func (s *AgentServer) Chat(ctx context.Context, in *agent.ChatRequest) (*agent.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

// 列出用户所有会话
func (s *AgentServer) ListSessions(ctx context.Context, in *agent.ListSessionsRequest) (*agent.ListSessionsResponse, error) {
	l := logic.NewListSessionsLogic(ctx, s.svcCtx)
	return l.ListSessions(in)
}

// 删除会话
func (s *AgentServer) DeleteSession(ctx context.Context, in *agent.DeleteSessionRequest) (*agent.DeleteSessionResponse, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}
