// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: like.proto

package likeclient

import (
	"context"

	"xls/app/like/rpc/like"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Error        = like.Error
	LikeRequest  = like.LikeRequest
	LikeResponse = like.LikeResponse

	Like interface {
		Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	client := like.NewLikeClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}
