// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: like.proto

package server

import (
	"context"

	"xls/app/like/rpc/internal/logic"
	"xls/app/like/rpc/internal/svc"
	"xls/app/like/rpc/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) Like(ctx context.Context, in *like.LikeRequest) (*like.LikeResponse, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}
