// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"
	logic2 "xls/app/user/rpc/internal/logic"
	"xls/app/user/rpc/internal/svc"
	user2 "xls/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user2.RegisterRequest) (*user2.RegisterResponse, error) {
	l := logic2.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user2.LoginRequest) (*user2.LoginResponse, error) {
	l := logic2.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user2.UserInfoRequest) (*user2.UserInfoResponse, error) {
	l := logic2.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
