// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CommentRequest struct {
	TargetID     uint64 `json:"target_id"`
	TargetUserID uint64 `json:"target_user_id"`
	ParentID     uint64 `json:"parent_id"`
	Content      string `json:"content"`
}

type CommentResponse struct {
	Status
}

type FansItem struct {
	FansUserID  uint64 `json:"fans_user_id"`
	FollowCount int64  `json:"follow_count"`
	FansCount   int64  `json:"fans_count"`
	CreateTime  int64  `json:"create_time"`
}

type FansListRequest struct {
	Cursor     int64  `json:"cursor"`
	PageSize   int64  `json:"page_size"`
	LastFansID uint64 `json:"last_fans_id"`
}

type FansListResponse struct {
	Status
	Fans       []FansItem `json:"fans"`
	Cursor     int64      `json:"cursor"`
	IsEnd      bool       `json:"is_end"`
	LastFansID uint64     `json:"last_fans_id"`
}

type FollowItem struct {
	ID             uint64 `json:"id"`
	FollowedUserID uint64 `json:"follow_user_id"`
	FansCount      int64  `json:"fans_count"`
	CreateTime     int64  `json:"create_time"`
}

type FollowListRequest struct {
	ID       uint64 `json:"id"`
	Cursor   int64  `json:"cursor"`
	PageSize int64  `json:"page_size"`
}

type FollowListResponse struct {
	Status
	Follows []FollowItem `json:"follows"`
	Cursor  int64        `json:"cursor"`
	IsEnd   bool         `json:"is_end"`
	ID      uint64       `json:"id"`
}

type FollowRequest struct {
	FollowedUserID uint64 `json:"followed_user_id"`
}

type FollowResponse struct {
	Status
}

type HotVideoListRequest struct {
}

type HotVideoListResponse struct {
	Status
	VideoList []VideoItem `json:"video_list"`
}

type LikeRequest struct {
	TargetID   uint64 `json:"target_id"`
	TargetType int32  `json:"target_type"`
}

type LikeResponse struct {
	Status
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Status
	Token
	UserID int `json:"user_id"`
}

type PublishVideoRequest struct {
	Url   string `json:"url"`
	Title string `json:"title"`
}

type PublishVideoResponse struct {
	Status
	VideoID int `json:"video_id"`
}

type RegisterRequest struct {
	Email            string `json:"email"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	Status
	Token
	UserID int `json:"user_id"`
}

type Status struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type Token struct {
	AccessToken string `json:"access_token"`
	ExpireAt    int64  `json:"expire_at"`
}

type UnFollowRequest struct {
	FollowedUserID uint64 `json:"followed_user_id"`
}

type UnFollowResponse struct {
	Status
}

type UploadVideoRequest struct {
}

type UploadVideoResponse struct {
	Status
	Url string `json:"url"`
}

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
	Status
}

type VideoItem struct {
	VideoID    int32  `json:"video_id"`
	AuthorID   int32  `json:"author_id"`
	Title      string `json:"title"`
	Url        string `json:"url"`
	LikeNum    int32  `json:"like_num"`
	CommentNum int32  `json:"comment_num"`
}
