// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Status
	Token
	UserID int `json:"user_id"`
}

type RegisterRequest struct {
	Email            string `json:"email"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	Status
	Token
	UserID int `json:"user_id"`
}

type Status struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type Token struct {
	AccessToken string `json:"access_tokeb"`
	ExpireAt    int64  `json:"expire_at"`
}

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
	Status
}
