// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: agent.proto

package agentclient

import (
	"context"

	"xls/app/agent/rpc/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatRequest           = agent.ChatRequest
	ChatResponse          = agent.ChatResponse
	DeleteSessionRequest  = agent.DeleteSessionRequest
	DeleteSessionResponse = agent.DeleteSessionResponse
	HealthCheckRequest    = agent.HealthCheckRequest
	HealthCheckResponse   = agent.HealthCheckResponse
	ListSessionsRequest   = agent.ListSessionsRequest
	ListSessionsResponse  = agent.ListSessionsResponse
	SessionMeta           = agent.SessionMeta
	VideoItem             = agent.VideoItem

	Agent interface {
		// 健康检查
		HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
		// 对话
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
		// 列出用户所有会话
		ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
		// 删除会话
		DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

// 健康检查
func (m *defaultAgent) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}

// 对话
func (m *defaultAgent) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

// 列出用户所有会话
func (m *defaultAgent) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListSessions(ctx, in, opts...)
}

// 删除会话
func (m *defaultAgent) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.DeleteSession(ctx, in, opts...)
}
