// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: video.proto

package server

import (
	"context"

	"xls/app/video/rpc/video/internal/logic"
	"xls/app/video/rpc/video/internal/svc"
	"xls/app/video/rpc/video/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Ping(ctx context.Context, in *video.Request) (*video.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
