// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: video.proto

package videoclient

import (
	"context"

	"xls/app/video/rpc/video/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Error                = video.Error
	HotVideoListRequest  = video.HotVideoListRequest
	HotVideoListResponse = video.HotVideoListResponse
	PublishRequest       = video.PublishRequest
	PublishResponse      = video.PublishResponse
	SearchVideoRequest   = video.SearchVideoRequest
	SearchVideoResponse  = video.SearchVideoResponse
	VideoItem            = video.VideoItem

	Video interface {
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
		HotVideoList(ctx context.Context, in *HotVideoListRequest, opts ...grpc.CallOption) (*HotVideoListResponse, error)
		SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultVideo) HotVideoList(ctx context.Context, in *HotVideoListRequest, opts ...grpc.CallOption) (*HotVideoListResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.HotVideoList(ctx, in, opts...)
}

func (m *defaultVideo) SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SearchVideo(ctx, in, opts...)
}
