// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: video.proto

package videoclient

import (
	"context"

	"xls/app/video/rpc/video/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Dimension                     = video.Dimension
	Error                         = video.Error
	GetVideoListRequest           = video.GetVideoListRequest
	GetVideoListResponse          = video.GetVideoListResponse
	GetVideosByDimensionsRequest  = video.GetVideosByDimensionsRequest
	GetVideosByDimensionsResponse = video.GetVideosByDimensionsResponse
	GetVideosByTagRequest         = video.GetVideosByTagRequest
	GetVideosByTagResponse        = video.GetVideosByTagResponse
	GetVideosByTagsRequest        = video.GetVideosByTagsRequest
	GetVideosByTagsResponse       = video.GetVideosByTagsResponse
	PublishRequest                = video.PublishRequest
	PublishResponse               = video.PublishResponse
	SearchVideoRequest            = video.SearchVideoRequest
	SearchVideoResponse           = video.SearchVideoResponse
	VideoItem                     = video.VideoItem

	Video interface {
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
		GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
		SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error)
		GetVideosByDimensions(ctx context.Context, in *GetVideosByDimensionsRequest, opts ...grpc.CallOption) (*GetVideosByDimensionsResponse, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultVideo) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

func (m *defaultVideo) SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SearchVideo(ctx, in, opts...)
}

func (m *defaultVideo) GetVideosByDimensions(ctx context.Context, in *GetVideosByDimensionsRequest, opts ...grpc.CallOption) (*GetVideosByDimensionsResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideosByDimensions(ctx, in, opts...)
}
